import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import Header from '../components/Header';
import { appStyles, colors } from '../styles/theme';

export default function Perfil({ navigation }) {
  function logout() { Alert.alert('Sair da conta', 'Deseja encerrar sua sessão?', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Sair', style: 'destructive', onPress: () => navigation.getParent()?.replace?.('Login') || navigation.navigate('Login') }]); }
  return <View style={[appStyles.screen, styles.screen]}><Header eyebrow="Minha conta" title="Perfil" /><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>MR</Text></View><Text style={styles.name}>Morador Safe RMR</Text><Text style={styles.email}>morador@email.com</Text></View><View style={styles.data}><Row label="Nome" value="Morador Safe RMR" /><Row label="Email" value="morador@email.com" /><Row label="Telefone" value="(81) 99999-9999" /></View><Option title="Editar perfil" onPress={() => Alert.alert('Em breve', 'A edição ficará disponível com o Supabase.')} /><Option title="Alterar senha" onPress={() => Alert.alert('Em breve', 'A recuperação será conectada ao Supabase Auth.')} /><Option title="Sair" danger onPress={logout} /></View>;
}
function Row({ label, value }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
function Option({ title, onPress, danger }) { return <Pressable onPress={onPress} style={styles.option}><Text style={[styles.optionText, danger && { color: colors.red }]}>{title}</Text><Text style={styles.arrow}>›</Text></Pressable>; }
const styles = StyleSheet.create({ screen: { padding: 20 }, profile: { alignItems: 'center', backgroundColor: colors.sky, borderRadius: 18, marginBottom: 18, padding: 22 }, avatar: { alignItems: 'center', backgroundColor: colors.blue, borderRadius: 36, height: 72, justifyContent: 'center', width: 72 }, avatarText: { color: colors.surface, fontSize: 23, fontWeight: '900' }, name: { color: colors.ink, fontSize: 18, fontWeight: '900', marginTop: 12 }, email: { color: colors.muted, fontSize: 13, marginTop: 4 }, data: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, marginBottom: 14, paddingHorizontal: 16 }, row: { borderBottomColor: colors.border, borderBottomWidth: 1, paddingVertical: 13 }, label: { color: colors.muted, fontSize: 11, fontWeight: '700' }, value: { color: colors.ink, fontSize: 15, marginTop: 4 }, option: { alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 18 }, optionText: { color: colors.ink, fontSize: 15, fontWeight: '700' }, arrow: { color: colors.muted, fontSize: 24 } });
