import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import Header from '../components/Header';
import { appStyles, colors } from '../styles/theme';

const services = [{ name: 'Defesa Civil', number: '199', color: colors.blue, description: 'Emergências e áreas de risco' }, { name: 'Bombeiros', number: '193', color: colors.red, description: 'Resgate e incêndios' }, { name: 'SAMU', number: '192', color: colors.green, description: 'Urgências médicas' }];
export default function SOS() {
  return <View style={[appStyles.screen, styles.screen]}><Header eyebrow="Emergência" title="SOS" /><Text style={styles.intro}>Em uma situação de risco, ligue diretamente para um serviço de emergência.</Text>{services.map((service) => <Pressable key={service.number} onPress={() => Linking.openURL(`tel:${service.number}`)} style={({ pressed }) => [styles.service, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: service.color }]}><Text style={styles.phone}>☎</Text></View><View style={styles.copy}><Text style={styles.name}>{service.name}</Text><Text style={styles.description}>{service.description}</Text></View><Text style={[styles.number, { color: service.color }]}>{service.number}</Text></Pressable>)}<Text style={styles.note}>Toque em um serviço para iniciar a ligação.</Text></View>;
}
const styles = StyleSheet.create({ screen: { padding: 20 }, intro: { color: colors.muted, fontSize: 15, lineHeight: 22, marginBottom: 22 }, service: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, flexDirection: 'row', marginBottom: 12, padding: 15 }, pressed: { opacity: 0.75 }, icon: { alignItems: 'center', borderRadius: 24, height: 48, justifyContent: 'center', width: 48 }, phone: { color: colors.surface, fontSize: 21 }, copy: { flex: 1, marginLeft: 13 }, name: { color: colors.ink, fontSize: 16, fontWeight: '800' }, description: { color: colors.muted, fontSize: 12, marginTop: 4 }, number: { fontSize: 20, fontWeight: '900' }, note: { color: colors.muted, fontSize: 12, marginTop: 10, textAlign: 'center' } });
