import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import Header from '../components/Header';
import { appStyles, colors } from '../styles/theme';

const services = [{ name: 'Defesa Civil', number: '199', color: colors.blue, description: 'Emergências e áreas de risco' }, { name: 'Bombeiros', number: '193', color: colors.red, description: 'Resgate e incêndios' }, { name: 'SAMU', number: '192', color: colors.green, description: 'Urgências médicas' }];
export default function SOS() {
  return <View style={[appStyles.screen, styles.screen]}><Header eyebrow="Emergência" title="SOS" /><View style={styles.banner}><Text style={styles.bannerIcon}>!</Text><View><Text style={styles.bannerTitle}>Precisa de ajuda?</Text><Text style={styles.bannerText}>Toque em um serviço para ligar agora.</Text></View></View><Text style={styles.intro}>Canais oficiais para situações de emergência e áreas de risco.</Text>{services.map((service) => <Pressable accessibilityRole="button" accessibilityLabel={`Ligar para ${service.name}, ${service.number}`} key={service.number} onPress={() => Linking.openURL(`tel:${service.number}`)} style={({ pressed }) => [styles.service, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: service.color }]}><Text style={styles.phone}>{service.name === 'Defesa Civil' ? '⌖' : service.name === 'Bombeiros' ? '◆' : '+'}</Text></View><View style={styles.copy}><Text style={styles.name}>{service.name}</Text><Text style={styles.description}>{service.description}</Text></View><View style={styles.call}><Text style={[styles.number, { color: service.color }]}>{service.number}</Text><Text style={styles.callLabel}>LIGAR</Text></View></Pressable>)}</View>;
}
const styles = StyleSheet.create({ screen: { padding: 20 }, banner: { alignItems: 'center', backgroundColor: '#FEF2F2', borderColor: '#FECACA', borderRadius: 16, borderWidth: 1, flexDirection: 'row', marginBottom: 18, padding: 14 }, bannerIcon: { alignItems: 'center', backgroundColor: colors.red, borderRadius: 15, color: colors.surface, fontSize: 18, fontWeight: '900', height: 30, marginRight: 11, paddingTop: 3, textAlign: 'center', width: 30 }, bannerTitle: { color: colors.redDark, fontSize: 14, fontWeight: '900' }, bannerText: { color: '#991B1B', fontSize: 12, marginTop: 3 }, intro: { color: colors.muted, fontSize: 14, lineHeight: 21, marginBottom: 17 }, service: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 18, borderWidth: 1, elevation: 2, flexDirection: 'row', marginBottom: 13, padding: 16, shadowColor: colors.navy, shadowOpacity: 0.07, shadowRadius: 8 }, pressed: { opacity: 0.78 }, icon: { alignItems: 'center', borderRadius: 26, height: 52, justifyContent: 'center', width: 52 }, phone: { color: colors.surface, fontSize: 23, fontWeight: '900' }, copy: { flex: 1, marginLeft: 13 }, name: { color: colors.ink, fontSize: 16, fontWeight: '900' }, description: { color: colors.muted, fontSize: 12, marginTop: 5 }, call: { alignItems: 'flex-end', marginLeft: 8 }, number: { fontSize: 23, fontWeight: '900' }, callLabel: { color: colors.muted, fontSize: 9, fontWeight: '900', letterSpacing: 1, marginTop: 2 } });
